#cmakedefine CRAY_STACKSEG_END
#cmakedefine C_ALLOCA
#cmakedefine DEFINE_XOPEN_SOURCE
#cmakedefine HAVE_ALLOCA
#cmakedefine HAVE_ALLOCA_H
#cmakedefine HAVE_CHMOD
#cmakedefine HAVE_CRT_EXTERNS_H
#cmakedefine HAVE_CRYPT
#cmakedefine HAVE_CRYPT_H
#cmakedefine HAVE_EXECINFO_H
#cmakedefine HAVE_FCNTL_H
#cmakedefine HAVE_GETRLIMIT
#cmakedefine HAVE_H_ERRNO
#cmakedefine HAVE_INITGROUPS
#cmakedefine HAVE_INTTYPES_H
#cmakedefine HAVE_LIBCRYPT
#cmakedefine HAVE_LIBNSL
#cmakedefine HAVE_LIBPTHREAD
#cmakedefine HAVE_LIBPTHREADGC
#cmakedefine HAVE_LIBPTHREADGC2
#cmakedefine HAVE_LIBSOCKET
#cmakedefine HAVE_MALLINFO
#cmakedefine HAVE_MALLOC_H
#cmakedefine HAVE_MALLOC_INFO
#cmakedefine HAVE_MEMORY_H
#cmakedefine HAVE_NETINET_TCP_H
#cmakedefine HAVE_OPEN_MEMSTREAM
#cmakedefine HAVE_PIPE2
#cmakedefine HAVE_POLL
#cmakedefine HAVE_POLL_H
#cmakedefine HAVE_PRCTL
#cmakedefine HAVE_SETGROUPS
#cmakedefine HAVE_SETPGID
#cmakedefine HAVE_SETPGRP
#cmakedefine HAVE_SETSID
#cmakedefine HAVE_SOCKET
#cmakedefine HAVE_SOCKLEN_T
#cmakedefine HAVE_SSIZE_T
#cmakedefine HAVE_STDINT_H
#cmakedefine HAVE_STDLIB_H
#cmakedefine HAVE_STRCASESTR
#cmakedefine HAVE_STRERROR
#cmakedefine HAVE_STRINGS_H
#cmakedefine HAVE_STRING_H
#cmakedefine HAVE_SYSCONF
#cmakedefine HAVE_SYSLOG_H
#cmakedefine HAVE_SYS_PRCTL_H
#cmakedefine HAVE_SYS_RESOURCE_H
#cmakedefine HAVE_SYS_STAT_H
#cmakedefine HAVE_SYS_TIME_H
#cmakedefine HAVE_SYS_TYPES_H
#cmakedefine HAVE_SYS_WAIT_H
#cmakedefine HAVE_UNISTD_H
#cmakedefine HAVE_UTIME
#cmakedefine HAVE_UTIME_H
#cmakedefine HAVE_VFORK
#cmakedefine HAVE__NSGETENVIRON
#cmakedefine O_PLMT
#cmakedefine PL_ARITY_AS_SIZE
#cmakedefine SETPGRP_VOID
#cmakedefine SIZEOF_LONG
#cmakedefine SIZEOF_LONG_LONG
#cmakedefine STACK_DIRECTION
#cmakedefine STDC_HEADERS
#cmakedefine HAVE_UUID_H
#cmakedefine HAVE_OSSP_UUID_H
#cmakedefine _REENTRANT
#cmakedefine size_t
